# Site settings
title: ASP.NET Web API for OData V4 Docs
email: odatafeedback@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  Complete documentations for ASP.NET Web API for OData V4
baseurl: "/webapidoc" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: pygments

permalink: /:title/